baseURL = "https://dev-sec.io/"
languageCode = "en-us"
title = "DevSec Hardening Framework"
theme = "devsec"
metaDataFormat = "yaml"

[[menu.global]]
  name = "About"
  weight = 1
  identifier = "project"
  url = "/project/"

[[menu.global]]
  name = "Tools"
  weight = 2
  identifier = "inspec_tools"
  url = "/inspec_tools"

[[menu.global]]
  name = "Applications"
  weight = 3
  identifier = "application"
  url = "/application/"

[[menu.sub]]
  name = "Vulcan"
  parent = "application"
  weight = 3
  identifier = "vulcan"
  url = "/application/vulcan/"

[[menu.global]]
  name = "Baselines"
  weight = 4
  identifier = "baselines"
  url = "/baselines/"

[[menu.global]]
  name = "Videos"
  weight = 5
  identifier = "videos"
  url = "/videos/"

[[menu.global]]
  name = "Community"
  weight = 6
  identifier = "comunity"
  url = "/community/"

[[menu.global]]
  name = "News"
  weight = 7
  identifier = "blog"
  url = "/blog/"

[[menu.global]]
  name = "GitHub"
  weight = 8
  identifier = "github"
  url = "https://github.com/mitre/mitre-inspec.github.io"
